# This file was generated by Gemini 3.1 Pro
#  and extended by Claude Sonnet 4.6
import argparse
import random
import re
import stim
import sys


def _build_obs_dem_from_base(base_dem, obs_idx, det_offset, x_shift):
    """
    Return a list of DEM instruction strings for observable `obs_idx`,
    derived from `base_dem` (a flat single-observable DEM).

    Transforms applied to each instruction:
      detector(x, ..., round) D{k}
        -> detector(x+x_shift, ..., round, float(obs_idx)) D{k+det_offset}
      error(p) D{a} ... L{m} ...
        -> error(p) D{a+det_offset} ... L{m+obs_idx} ...
    Separators (^) and other structure are preserved unchanged.
    """
    _d_pat = re.compile(r'\bD(\d+)\b')
    _l_pat = re.compile(r'\bL(\d+)\b')
    lines = []
    for inst in base_dem:
        s = str(inst)
        if s.startswith('detector('):
            args = list(inst.args_copy())
            args[0] = args[0] + x_shift
            args.append(float(obs_idx))
            new_det_ids = [t.val + det_offset
                           for t in inst.targets_copy()
                           if t.is_relative_detector_id()]
            args_str = ', '.join(str(a) for a in args)
            dets_str = ' '.join(f'D{k}' for k in new_det_ids)
            lines.append(f'detector({args_str}) {dets_str}')
        elif s.startswith('error('):
            s = _d_pat.sub(lambda m: f'D{int(m.group(1)) + det_offset}', s)
            s = _l_pat.sub(lambda m: f'L{int(m.group(1)) + obs_idx}', s)
            lines.append(s)
        # else: skip (logical_observable annotations, shift_detectors remnants, etc.)
    return lines


def build_multi_obs_dem(base_dem, num_observables, x_shift):
    """
    Build a multi-observable DEM in observable-major order:
      [obs0 dets][obs1 dets]...[obsN-1 dets]
    K = base_dem.num_detectors detectors per observable.
    """
    K = base_dem.num_detectors
    all_lines = []
    for i in range(num_observables):
        all_lines.extend(_build_obs_dem_from_base(base_dem, i, i * K, i * x_shift))
    return stim.DetectorErrorModel('\n'.join(all_lines))


def _build_obs_round_index(dem):
    """Return obs_round_dets[(obs_id, round)] = [(det_id, coors)], sorted by x."""
    coords_map = dem.get_detector_coordinates(set(range(dem.num_detectors)))
    obs_round_dets = {}
    for det_id, coors in coords_map.items():
        if len(coors) < 2:
            continue
        obs_id = int(round(coors[-1]))   # last coord = observable_id
        rnd = coors[-2]                  # second-to-last = round
        obs_round_dets.setdefault((obs_id, rnd), []).append((det_id, list(coors)))
    for key in obs_round_dets:
        obs_round_dets[key].sort(key=lambda x: x[1][0])  # sort by x-coordinate
    return obs_round_dets


def _obs_x_extremes(obs_round_dets):
    """Return {obs_id: (global_max_x, global_min_x)} across all rounds."""
    result = {}
    for (obs_id, _), dets in obs_round_dets.items():
        xs = [c[0] for _, c in dets]
        if obs_id not in result:
            result[obs_id] = (max(xs), min(xs))
        else:
            old_max, old_min = result[obs_id]
            result[obs_id] = (max(old_max, max(xs)), min(old_min, min(xs)))
    return result


def _boundary_dets_at_round(obs_round_dets, obs_id, rnd, x_limit, is_right_side, x_threshold):
    """
    Return detectors of obs_id at the given round that lie within x_threshold of x_limit.
    is_right_side=True  -> keep dets with x >= x_limit - x_threshold  (right boundary of obs_a)
    is_right_side=False -> keep dets with x <= x_limit + x_threshold  (left boundary of obs_b)

    Sorting ensures the actual edge sites pair first:
    - Right side: sort by y then DESCENDING x, so the rightmost site (closest to seam)
      comes first and pairs with the leftmost site of the opposite patch.
    - Left side:  sort by y then ASCENDING x, so the leftmost site comes first.
    For 3-D detectors (repetition code, no y), the same logic applies to x alone.
    This guarantees that, with x_threshold > 0, the true boundary sites pair with
    each other and interior sites pair with each other secondarily.
    """
    dets = obs_round_dets.get((obs_id, rnd), [])
    if is_right_side:
        filtered = [(d, c) for d, c in dets if c[0] >= x_limit - x_threshold]
    else:
        filtered = [(d, c) for d, c in dets if c[0] <= x_limit + x_threshold]
    if not filtered:
        return filtered
    ndim = len(filtered[0][1])
    if ndim >= 4:
        # Surface code: sort by y first (matching positions along seam),
        # then by x with direction depending on which boundary side.
        if is_right_side:
            filtered.sort(key=lambda x: (x[1][1], -x[1][0]))  # y asc, x desc
        else:
            filtered.sort(key=lambda x: (x[1][1],  x[1][0]))  # y asc, x asc
    else:
        # Repetition code (no y): sort by x with direction depending on side.
        if is_right_side:
            filtered.sort(key=lambda x: -x[1][0])  # x desc: rightmost first
        else:
            filtered.sort(key=lambda x:  x[1][0])  # x asc:  leftmost first
    return filtered


def generate_random_surgery_gates(num_patches, available_rounds, num_gates,
                                   duration=1, seed=42):
    """
    Randomly generate surgery gate specs: list of (obs_a, obs_b, start_round, duration).

    A gate occupies its two observables for [start_round, start_round+duration) rounds.
    Constraint: at each round, each observable is in at most one active gate.
    obs_a < obs_b always.  Duplicate gate keys are rejected.

    Prints a warning if fewer than num_gates gates can be placed.
    """
    rng = random.Random(seed)
    gates = []
    gate_set = set()
    obs_occupied = {}   # obs_id -> set of rounds it is busy

    # Precompute a list of valid start rounds (those with at least `duration` coverage)
    sorted_rounds = sorted(available_rounds)

    max_attempts = num_gates * 500
    for _ in range(max_attempts):
        if len(gates) >= num_gates:
            break
        start_rnd = rng.choice(sorted_rounds)
        obs_a = rng.randint(0, num_patches - 1)
        obs_b = rng.randint(0, num_patches - 1)
        if obs_a == obs_b:
            continue
        obs_a, obs_b = min(obs_a, obs_b), max(obs_a, obs_b)

        # Rounds that this gate would occupy (from available_rounds within the window)
        gate_rounds = [r for r in sorted_rounds
                       if start_rnd <= r < start_rnd + duration]
        if not gate_rounds:
            gate_rounds = [min(sorted_rounds, key=lambda r: abs(r - start_rnd))]

        occ_a = obs_occupied.get(obs_a, set())
        occ_b = obs_occupied.get(obs_b, set())
        if any(r in occ_a or r in occ_b for r in gate_rounds):
            continue

        key = (obs_a, obs_b, start_rnd, duration)
        if key in gate_set:
            continue

        gate_set.add(key)
        gates.append(key)
        for r in gate_rounds:
            obs_occupied.setdefault(obs_a, set()).add(r)
            obs_occupied.setdefault(obs_b, set()).add(r)

    if len(gates) < num_gates:
        print(f"WARNING: could only place {len(gates)}/{num_gates} surgery gates "
              f"(constraint: each observable in at most one gate per round).",
              file=sys.stderr)
    return gates


def parse_surgery_spec(spec_str, default_duration=1):
    """
    Parse a manual surgery spec string into a list of (obs_a, obs_b, start_round, duration).
    Format: semicolon-separated entries of "obs_a,obs_b,start[,duration]".
    Duration is optional and defaults to default_duration.
    Example: "0,1,3,2;0,2,7"  -> [(0,1,3,2), (0,2,7,1)]
    """
    gates = []
    for entry in spec_str.strip().split(";"):
        entry = entry.strip()
        if not entry:
            continue
        parts = entry.split(",")
        if len(parts) not in (3, 4):
            raise ValueError(
                f"Invalid surgery spec entry '{entry}'; expected 'obs_a,obs_b,start[,duration]'")
        obs_a, obs_b, start = int(parts[0]), int(parts[1]), int(parts[2])
        dur = int(parts[3]) if len(parts) == 4 else default_duration
        if obs_a == obs_b:
            raise ValueError(f"obs_a == obs_b in surgery spec '{entry}'")
        if dur < 1:
            raise ValueError(f"duration must be >= 1 in surgery spec '{entry}'")
        gates.append((min(obs_a, obs_b), max(obs_a, obs_b), start, dur))
    return gates


def inject_cross_obs_into_dem(dem, surgery_gates, p_cross=0.001, x_boundary_threshold=2):
    """
    Written by Claude Sonnet 4.6
    Inject cross-observable error mechanisms into the DEM to simulate lattice surgery gates.

    Each gate is a (obs_a, obs_b, start_round, duration) tuple.  For each round in the
    gate's window this function:
      - Finds all boundary detectors of obs_a (rightmost by x) and obs_b (leftmost by x)
        within x_boundary_threshold of their respective patch edges.
      - Pairs them by y-coordinate (or x for codes with no y coord).
      - For each pair creates one seam detector (observable_id = -(obs_a+obs_b)/2) at the
        spatial midpoint.
      - Adds error edges: obs_a_det <-> seam_det  and  seam_det <-> obs_b_det.
      - Adds temporal error edges connecting each seam detector to the corresponding seam
        detector from the previous round (forming a temporal chain along the seam).
      - Removes the boundary error edges from seam-adjacent nodes so the decoder routes
        through the seam rather than to the code boundary.

    Args:
        dem:                   stim.DetectorErrorModel from build_multi_obs_dem
        surgery_gates:         list of (obs_a, obs_b, start_round, duration); obs_a < obs_b
        p_cross:               error probability for all seam error edges
        x_boundary_threshold:  x-distance from patch edge within which detectors are
                               considered boundary detectors (default 2)

    Returns:
        stim.DetectorErrorModel with injected cross-observable instructions appended.
    """
    if not surgery_gates:
        return dem

    obs_round_dets = _build_obs_round_index(dem)
    x_extremes = _obs_x_extremes(obs_round_dets)

    obs_rounds = {}
    for (obs_id, rnd) in obs_round_dets:
        obs_rounds.setdefault(obs_id, []).append(rnd)
    for obs_id in obs_rounds:
        obs_rounds[obs_id].sort()

    new_det_id = dem.num_detectors
    new_lines = []
    seam_adjacent_ids = set()

    for obs_a, obs_b, start_round, duration in surgery_gates:
        if obs_a not in x_extremes or obs_b not in x_extremes:
            print(f"WARNING: obs {obs_a} or {obs_b} not found in DEM; "
                  f"skipping gate ({obs_a},{obs_b},{start_round},{duration}).", file=sys.stderr)
            continue

        max_x_a = x_extremes[obs_a][0]   # rightmost x of obs_a's patch
        min_x_b = x_extremes[obs_b][1]   # leftmost  x of obs_b's patch

        rounds_a = obs_rounds.get(obs_a, [])
        rounds_b = obs_rounds.get(obs_b, [])

        # site_idx -> seam det_id from previous round (for temporal chaining)
        prev_seam_by_site = {}

        for step in range(duration):
            target_rnd = start_round + step

            # Snap each side to the closest available round
            rnd_a = min(rounds_a, key=lambda r: abs(r - target_rnd)) if rounds_a else None
            rnd_b = min(rounds_b, key=lambda r: abs(r - target_rnd)) if rounds_b else None
            if rnd_a is None or rnd_b is None:
                prev_seam_by_site = {}
                continue

            bdets_a = _boundary_dets_at_round(
                obs_round_dets, obs_a, rnd_a, max_x_a, is_right_side=True,
                x_threshold=x_boundary_threshold)
            bdets_b = _boundary_dets_at_round(
                obs_round_dets, obs_b, rnd_b, min_x_b, is_right_side=False,
                x_threshold=x_boundary_threshold)

            if not bdets_a or not bdets_b:
                prev_seam_by_site = {}   # gap — reset temporal chain
                continue

            n_pairs = min(len(bdets_a), len(bdets_b))
            new_prev = {}

            for site_i in range(n_pairs):
                d_a_id, c_a = bdets_a[site_i]
                d_b_id, c_b = bdets_b[site_i]

                # Seam detector coordinates:
                # - x (k=0): evenly spaced across the seam gap [max_x_a, min_x_b]
                #   so that multiple seam detectors at the same round don't overlap.
                # - y and other spatial coords (k>=1): midpoint of the paired sites.
                # - second-to-last: round from obs_a.
                # - last: -(obs_a+obs_b)/2 < 0 (cross-obs encoding for diagram/decoder).
                ndim = len(c_a)
                x_seam = max_x_a + (min_x_b - max_x_a) * (site_i + 1) / (n_pairs + 1)
                seam_coors = [x_seam]
                for k in range(1, ndim - 2):
                    seam_coors.append((c_a[k] + c_b[k]) / 2)
                seam_coors.append(float(rnd_a))
                seam_coors.append(-(obs_a + obs_b) / 2.0)

                coors_str = ", ".join(str(c) for c in seam_coors)
                new_lines.append(f"detector({coors_str}) D{new_det_id}")

                seam_adjacent_ids.add(d_a_id)
                seam_adjacent_ids.add(d_b_id)

                # Lateral edges to each patch
                new_lines.append(f"error({p_cross}) D{d_a_id} D{new_det_id}")
                new_lines.append(f"error({p_cross}) D{new_det_id} D{d_b_id}")

                # Temporal edge within the seam (previous round -> this round, same site)
                if site_i in prev_seam_by_site:
                    new_lines.append(
                        f"error({p_cross}) D{prev_seam_by_site[site_i]} D{new_det_id}")

                new_prev[site_i] = new_det_id
                new_det_id += 1

            prev_seam_by_site = new_prev

    if not new_lines:
        return dem

    # Flatten the input DEM before appending seam lines.  The input from
    # build_multi_obs_dem is already flat, but this guards against any repeat
    # blocks surviving from other paths.
    flat_dem = dem.flattened()

    # Remove boundary error edges (exactly one D target per component) from
    # seam-adjacent nodes.  These nodes now connect to the seam; keeping their
    # boundary edges would make the decoder prefer matching to the boundary.
    _d_pat = re.compile(r'\bD(\d+)\b')
    def _is_boundary_edge_for_seam_node(line):
        if not line.startswith('error('):
            return False
        # Check each '^'-decomposed component: if any has exactly one D target
        # pointing to a seam-adjacent node, drop the whole line.
        for comp in line.split('^'):
            d_ids = _d_pat.findall(comp)
            if len(d_ids) == 1 and int(d_ids[0]) in seam_adjacent_ids:
                return True
        return False

    flat_lines = str(flat_dem).splitlines()
    filtered_lines = [l for l in flat_lines if not _is_boundary_edge_for_seam_node(l)]
    dem_str = "\n".join(filtered_lines) + "\n" + "\n".join(new_lines)
    return stim.DetectorErrorModel(dem_str)


def main():
    parser = argparse.ArgumentParser(
        description="Generate a multi-observable matching graph DEM, optionally injecting "
                    "cross-observable lattice-surgery gates.")
    parser.add_argument("--rounds", type=int, required=True)
    parser.add_argument("--distance", type=int, required=True)
    parser.add_argument("--after_clifford_depolarization", type=float, default=0.01)
    parser.add_argument("--code", type=str, default="surface_code")
    parser.add_argument("--task", type=str, default="rotated_memory_x")
    parser.add_argument("--num_observables", type=int, default=2)

    surgery = parser.add_mutually_exclusive_group()
    surgery.add_argument("--num_surgery_gates", type=int, default=0,
                         help="Number of cross-observable surgery gates to inject, placed "
                              "randomly.  Each gate spans --surgery_duration rounds and "
                              "connects all boundary-site detector pairs along the shared "
                              "edge.")
    surgery.add_argument("--surgery_spec", type=str, default="",
                         help="Manual gate spec: semicolon-separated entries of the form "
                              "'obs_a,obs_b,start[,duration]' (duration defaults to "
                              "--surgery_duration).  Example: '0,1,3,2;0,2,7'.")

    parser.add_argument("--surgery_duration", type=int, default=4,
                        help="Default number of rounds per surgery gate (default 4).")
    parser.add_argument("--surgery_seed", type=int, default=42,
                        help="RNG seed for --num_surgery_gates placement (default 42).")
    parser.add_argument("--p_cross", type=float, default=None,
                        help="Error probability for each injected seam error edge. "
                             "Defaults to min(0.4, 2 * after_clifford_depolarization) so seam "
                             "edges are lighter than boundary edges.")
    parser.add_argument("--surgery_boundary_depth", type=int, default=2,
                        help="x-distance from patch edge for selecting boundary detectors "
                             "(default 2).")
    parser.add_argument("--circuit_out", type=str, default="",
                        help="If given, write the single-observable base circuit to this file "
                             "for reference.  The output to stdout is always a DEM.")
    args = parser.parse_args()

    has_surgery = args.num_surgery_gates > 0 or args.surgery_spec

    p_cross = args.p_cross if args.p_cross is not None else min(0.4, 2.0 * args.after_clifford_depolarization)

    base = stim.Circuit.generated(
        f"{args.code}:{args.task}",
        distance=args.distance,
        rounds=args.rounds,
        after_clifford_depolarization=args.after_clifford_depolarization
    )

    if args.circuit_out:
        with open(args.circuit_out, "w") as f:
            print(base, file=f)

    base_dem_flat = base.detector_error_model(decompose_errors=True).flattened()
    max_x = max(
        (inst.args_copy()[0] for inst in base_dem_flat
         if str(inst).startswith('detector(')),
        default=0.0)
    x_shift = max_x + 2

    dem = build_multi_obs_dem(base_dem_flat, args.num_observables, x_shift)

    if has_surgery:
        if args.surgery_spec:
            surgery_gates = parse_surgery_spec(args.surgery_spec,
                                               default_duration=args.surgery_duration)
        else:
            obs_round_dets = _build_obs_round_index(dem)
            available_rounds = sorted({rnd for (_, rnd) in obs_round_dets})
            surgery_gates = generate_random_surgery_gates(
                args.num_observables, available_rounds,
                args.num_surgery_gates,
                duration=args.surgery_duration,
                seed=args.surgery_seed)
        print(f"# Surgery gates: {surgery_gates}", file=sys.stderr)
        print(f"# p_cross: {p_cross:.6g}  (p={args.after_clifford_depolarization})",
              file=sys.stderr)
        dem = inject_cross_obs_into_dem(
            dem, surgery_gates, p_cross=p_cross,
            x_boundary_threshold=args.surgery_boundary_depth)

    print(dem)


if __name__ == '__main__':
    main()
