# This file was generated by Gemini 3.1 Pro
#  and Claude Sonnet 4.6
# Refactored to use file-native operations and Perl-based boundary filtering
import argparse
import os
import random
import re
import stim
import subprocess
import sys
import tempfile


def _build_obs_dem_from_base(base_dem, obs_idx, det_offset, x_shift):
    """
    Return a list of DEM instruction strings for observable `obs_idx`.

    Transforms applied to each instruction:
      detector(x, ..., round) D{k}
        -> detector(x+x_shift, ..., float(obs_idx), round) D{k+det_offset}
      error(p) D{a} ... L{m} ...
        -> error(p) D{a+det_offset} ... L{m+obs_idx} ...
    Separators (^) and other structure are preserved unchanged.
    """
    _d_pat = re.compile(r'\bD(\d+)\b')
    _l_pat = re.compile(r'\bL(\d+)\b')
    lines = []
    for inst in base_dem:
        s = str(inst)
        if s.startswith('detector('):
            args = list(inst.args_copy())
            args[0] = args[0] + x_shift
            args.insert(-1, float(obs_idx))
            new_det_ids = [t.val + det_offset
                           for t in inst.targets_copy()
                           if t.is_relative_detector_id()]
            args_str = ', '.join(str(int(a) if a == int(a) else a) for a in args)
            dets_str = ' '.join(f'D{k}' for k in new_det_ids)
            lines.append(f'detector({args_str}) {dets_str}')
        elif s.startswith('error('):
            s = _d_pat.sub(lambda m: f'D{int(m.group(1)) + det_offset}', s)
            s = _l_pat.sub(lambda m: f'L{int(m.group(1)) + obs_idx}', s)
            lines.append(s)
        # else: skip (logical_observable annotations, shift_detectors remnants, etc.)
    return lines


def build_multi_obs_dem(base_dem, num_observables, x_shift):
    """
    Build a multi-observable DEM in observable-major order:
      [obs0 dets][obs1 dets]...[obsN-1 dets]
    K = base_dem.num_detectors detectors per observable.
    """
    K = base_dem.num_detectors
    all_lines = []
    for i in range(num_observables):
        all_lines.extend(_build_obs_dem_from_base(base_dem, i, i * K, i * x_shift))
    return stim.DetectorErrorModel('\n'.join(all_lines))


def _write_obs_dem_to_file(base_dem, obs_idx, det_offset, x_shift, out_file):
    """Write one observable's transformed DEM instructions to an open text file."""
    for line in _build_obs_dem_from_base(base_dem, obs_idx, det_offset, x_shift):
        out_file.write(line)
        out_file.write("\n")


def build_obs_temp_files(base_dem, num_observables: int, x_shift: float) -> list[dict]:
    """
    Create one temp file per observable and return ordered metadata.
    
    Returns list of dicts in observable-major order:
      {"obs_id": int, "path": str, "det_start": int, "det_end": int}
    
    Observable i has detector IDs [i*K, (i+1)*K) where K = base_dem.num_detectors.
    """
    k_det = base_dem.num_detectors
    obs_files = []
    
    for i in range(num_observables):
        with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".dem") as tmp:
            _write_obs_dem_to_file(base_dem, i, i * k_det, i * x_shift, tmp)
            obs_files.append({
                "obs_id": i,
                "path": tmp.name,
                "det_start": i * k_det,
                "det_end": (i + 1) * k_det
            })
    
    return obs_files


def parse_obs_files_index(obs_files: list[dict]) -> tuple[dict, dict, dict, int]:
    """
    Single-pass parse of observable files building:
      - obs_round_dets[(obs_id, round)] -> list[(det_id, coors)] sorted by x
      - obs_rounds[obs_id] -> sorted list[round]
      - x_extremes[obs_id] -> (max_x, min_x)
      - max_detector_id
    
    Parses detector(...) lines from each obs file to extract metadata without
    loading the full DEM into memory.
    """
    obs_round_dets = {}
    obs_rounds = {}
    x_extremes = {}
    max_detector_id = -1
    
    _det_pat = re.compile(r'detector\(([^)]+)\)\s*D(\d+)')
    
    for obs_meta in obs_files:
        obs_id = obs_meta["obs_id"]
        path = obs_meta["path"]
        
        with open(path, 'r') as f:
            for line in f:
                m = _det_pat.match(line.strip())
                if not m:
                    continue
                
                args_str = m.group(1)
                det_id = int(m.group(2))
                max_detector_id = max(max_detector_id, det_id)
                
                # Parse coordinates: "x, ..., y?, ..., obs_id, round"
                try:
                    args = [float(a.strip()) for a in args_str.split(',')]
                except:
                    continue
                
                if len(args) < 2:
                    continue
                
                # Last arg is round, second-to-last is observable_id
                rnd = args[-1]
                parsed_obs_id = int(round(args[-2])) if len(args) >= 2 else obs_id
                
                if parsed_obs_id != obs_id:
                    continue
                
                coors = args  # Full coordinate list
                obs_round_dets.setdefault((obs_id, rnd), []).append((det_id, coors))
                obs_rounds.setdefault(obs_id, set()).add(rnd)
                
                x = coors[0]
                if obs_id not in x_extremes:
                    x_extremes[obs_id] = (x, x)
                else:
                    old_max, old_min = x_extremes[obs_id]
                    x_extremes[obs_id] = (max(old_max, x), min(old_min, x))
    
    # Sort detector lists by x-coordinate and convert obs_rounds sets to sorted lists
    for key in obs_round_dets:
        obs_round_dets[key].sort(key=lambda x: x[1][0])
    
    for obs_id in obs_rounds:
        obs_rounds[obs_id] = sorted(list(obs_rounds[obs_id]))
    
    return obs_round_dets, obs_rounds, x_extremes, max_detector_id


def build_available_rounds(obs_round_dets: dict) -> list:
    """Extract sorted unique rounds from parsed obs_round_dets."""
    rounds = set()
    for (_, rnd) in obs_round_dets.keys():
        rounds.add(rnd)
    return sorted(list(rounds))


def _boundary_dets_at_round(obs_round_dets, obs_id, rnd, x_limit, is_right_side, x_threshold):
    """
    Return detectors of obs_id at the given round within x_threshold of x_limit.
    is_right_side=True  -> keep dets with x >= x_limit - x_threshold  (right boundary)
    is_right_side=False -> keep dets with x <= x_limit + x_threshold  (left boundary)

    Sorting ensures proper pairing by y (or x for repetition codes).
    """
    dets = obs_round_dets.get((obs_id, rnd), [])
    if is_right_side:
        filtered = [(d, c) for d, c in dets if c[0] >= x_limit - x_threshold]
    else:
        filtered = [(d, c) for d, c in dets if c[0] <= x_limit + x_threshold]
    
    if not filtered:
        return filtered
    
    ndim = len(filtered[0][1])
    if ndim >= 4:
        # Surface code: sort by y first, then x
        if is_right_side:
            filtered.sort(key=lambda x: (x[1][1], -x[1][0]))  # y asc, x desc
        else:
            filtered.sort(key=lambda x: (x[1][1],  x[1][0]))  # y asc, x asc
    else:
        # Repetition code: sort by x only
        if is_right_side:
            filtered.sort(key=lambda x: -x[1][0])  # x desc
        else:
            filtered.sort(key=lambda x:  x[1][0])  # x asc
    
    return filtered


def write_seams_to_temp_file(obs_round_dets: dict, obs_rounds: dict, x_extremes: dict,
                             surgery_gates: list, p_cross: float, x_boundary_threshold: float,
                             seam_start_det_id: int, seam_file) -> dict[int, set[int]]:
    """
    Emit seam detector/error lines into seam_file, starting at seam_start_det_id.
    
    Returns seam_adjacent_by_obs:
      obs_id -> set(det_id) of detectors seam-adjacent for this observable
    """
    seam_adjacent_by_obs = {}
    new_det_id = seam_start_det_id
    
    for seam_idx, (obs_a, obs_b, start_round, duration) in enumerate(surgery_gates, start=1):
        if obs_a not in x_extremes or obs_b not in x_extremes:
            print(f"WARNING: obs {obs_a} or {obs_b} not found in DEM; "
                  f"skipping gate ({obs_a},{obs_b},{start_round},{duration}).", file=sys.stderr)
            continue
        
        max_x_a = x_extremes[obs_a][0]  # rightmost x of obs_a
        min_x_b = x_extremes[obs_b][1]  # leftmost x of obs_b
        
        rounds_a = obs_rounds.get(obs_a, [])
        rounds_b = obs_rounds.get(obs_b, [])
        
        prev_seam_by_site = {}
        
        for step in range(duration):
            target_rnd = start_round + step
            
            # Snap to nearest available round
            rnd_a = min(rounds_a, key=lambda r: abs(r - target_rnd)) if rounds_a else None
            rnd_b = min(rounds_b, key=lambda r: abs(r - target_rnd)) if rounds_b else None
            if rnd_a is None or rnd_b is None:
                prev_seam_by_site = {}
                continue
            
            bdets_a = _boundary_dets_at_round(
                obs_round_dets, obs_a, rnd_a, max_x_a, is_right_side=True,
                x_threshold=x_boundary_threshold)
            bdets_b = _boundary_dets_at_round(
                obs_round_dets, obs_b, rnd_b, min_x_b, is_right_side=False,
                x_threshold=x_boundary_threshold)
            
            if not bdets_a or not bdets_b:
                prev_seam_by_site = {}
                continue
            
            n_pairs = min(len(bdets_a), len(bdets_b))
            new_prev = {}
            
            for site_i in range(n_pairs):
                d_a_id, c_a = bdets_a[site_i]
                d_b_id, c_b = bdets_b[site_i]
                
                # Seam detector coordinates
                ndim = len(c_a)
                x_seam = max_x_a + (min_x_b - max_x_a) * (site_i + 1) / (n_pairs + 1)
                seam_coors = [x_seam]
                for k in range(1, ndim - 2):
                    seam_coors.append((c_a[k] + c_b[k]) / 2)
                seam_coors.append(-float(seam_idx))
                seam_coors.append(float(rnd_a))
                
                coors_str = ", ".join(str(int(c) if c == int(c) else c) for c in seam_coors)
                seam_file.write(f"detector({coors_str}) D{new_det_id}\n")
                
                # Track seam-adjacent detectors
                seam_adjacent_by_obs.setdefault(obs_a, set()).add(d_a_id)
                seam_adjacent_by_obs.setdefault(obs_b, set()).add(d_b_id)
                
                # Lateral edges
                seam_file.write(f"error({p_cross}) D{d_a_id} D{new_det_id}\n")
                seam_file.write(f"error({p_cross}) D{new_det_id} D{d_b_id}\n")
                
                # Temporal edge
                if site_i in prev_seam_by_site:
                    seam_file.write(
                        f"error({p_cross}) D{prev_seam_by_site[site_i]} D{new_det_id}\n")
                
                new_prev[site_i] = new_det_id
                new_det_id += 1
            
            prev_seam_by_site = new_prev
    
    return seam_adjacent_by_obs


def ensure_perl_available() -> None:
    """Validate perl exists; raise clear error if missing."""
    try:
        result = subprocess.run(["perl", "-v"], capture_output=True, timeout=5)
        if result.returncode != 0:
            raise RuntimeError("perl invocation failed")
    except FileNotFoundError:
        raise RuntimeError(
            "perl not found in PATH; required for in-place boundary filtering. "
            "Install perl or add it to your PATH."
        )
    except Exception as e:
        raise RuntimeError(f"perl check failed: {e}")


def perl_filter_boundary_edges_inplace(obs_path: str, seam_adjacent_ids: set[int]) -> None:
    """
    In-place perl filtering for one observable file.
    
    Drop error(...) line if any ^ component has exactly one D target
    and that detector is in seam_adjacent_ids.
    """
    if not seam_adjacent_ids:
        return  # Nothing to filter
    
    # Pass seam-adjacent detector IDs as comma-separated values for Perl hash lookup.
    det_ids_str = ",".join(str(d) for d in sorted(seam_adjacent_ids))
    
    perl_script = fr"""
my %seam_dets = map {{ $_ => 1 }} split /,/, "{det_ids_str}";

while (<>) {{
    if (/^\s*error\(/) {{
        my $drop = 0;
        for my $comp (split /\^/) {{
            my @dets = ($comp =~ /D(\d+)/g);
            if (@dets == 1 && exists $seam_dets{{$dets[0]}}) {{
                $drop = 1;
                last;
            }}
        }}
        next if $drop;
    }}
    print;
}}
"""
    
    # Write Perl script to temp file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.pl', delete=False) as pf:
        pf.write(perl_script)
        perl_script_path = pf.name
    
    try:
        # Run perl in-place: perl -i.bak script.pl file
        # We use -i without .bak to avoid backup files
        result = subprocess.run(
            ["perl", "-i", "-e", perl_script, obs_path],
            capture_output=True,
            timeout=60
        )
        if result.returncode != 0:
            raise RuntimeError(f"perl filtering failed: {result.stderr.decode()}")
    finally:
        try:
            os.remove(perl_script_path)
        except OSError:
            pass


def filter_impacted_obs_files_inplace(obs_files: list[dict], 
                                      seam_adjacent_by_obs: dict[int, set[int]]) -> None:
    """
    Apply perl filter only to observables present in seam_adjacent_by_obs.
    """
    for obs_meta in obs_files:
        obs_id = obs_meta["obs_id"]
        if obs_id not in seam_adjacent_by_obs:
            continue
        
        seam_adjacent_ids = seam_adjacent_by_obs[obs_id]
        perl_filter_boundary_edges_inplace(obs_meta["path"], seam_adjacent_ids)


def concat_files_to_stream(paths: list[str], out_stream) -> None:
    """Concatenate files to output stream in deterministic order."""
    for path in paths:
        try:
            with open(path, 'r') as f:
                while True:
                    chunk = f.read(1024 * 1024)
                    if not chunk:
                        break
                    out_stream.write(chunk)
        except Exception as e:
            print(f"WARNING: failed to read {path}: {e}", file=sys.stderr)


def cleanup_temp_files(paths: list[str]) -> None:
    """Best-effort cleanup of temp files."""
    for path in paths:
        try:
            os.remove(path)
        except OSError:
            pass


def generate_random_surgery_gates(num_patches, available_rounds, num_gates,
                                   duration=1, seed=42):
    """
    Randomly generate surgery gate specs: list of (obs_a, obs_b, start_round, duration).

    A gate occupies its two observables for [start_round, start_round+duration) rounds.
    Constraint: at each round, each observable is in at most one active gate.
    obs_a < obs_b always.  Duplicate gate keys are rejected.

    Prints a warning if fewer than num_gates gates can be placed.
    """
    rng = random.Random(seed)
    gates = []
    gate_set = set()
    obs_occupied = {}   # obs_id -> set of rounds it is busy

    # Precompute a list of valid start rounds (those with at least `duration` coverage)
    sorted_rounds = sorted(available_rounds)

    max_attempts = num_gates * 500
    for _ in range(max_attempts):
        if len(gates) >= num_gates:
            break
        start_rnd = rng.choice(sorted_rounds)
        obs_a = rng.randint(0, num_patches - 1)
        obs_b = rng.randint(0, num_patches - 1)
        if obs_a == obs_b:
            continue
        obs_a, obs_b = min(obs_a, obs_b), max(obs_a, obs_b)

        # Rounds that this gate would occupy (from available_rounds within the window)
        gate_rounds = [r for r in sorted_rounds
                       if start_rnd <= r < start_rnd + duration]
        if not gate_rounds:
            gate_rounds = [min(sorted_rounds, key=lambda r: abs(r - start_rnd))]

        occ_a = obs_occupied.get(obs_a, set())
        occ_b = obs_occupied.get(obs_b, set())
        if any(r in occ_a or r in occ_b for r in gate_rounds):
            continue

        key = (obs_a, obs_b, start_rnd, duration)
        if key in gate_set:
            continue

        gate_set.add(key)
        gates.append(key)
        for r in gate_rounds:
            obs_occupied.setdefault(obs_a, set()).add(r)
            obs_occupied.setdefault(obs_b, set()).add(r)

    if len(gates) < num_gates:
        print(f"WARNING: could only place {len(gates)}/{num_gates} surgery gates "
              f"(constraint: each observable in at most one gate per round).",
              file=sys.stderr)
    return gates


def build_surgery_spec_24obs(M=42, duration=21):
    """
    Generate the surgery spec string for the 24-observable, 756-round circuit.

    24 observables in 4 blocks of 6 (block b = obs 6b..6b+5, b in 0..3).
    M=42 → 18 local partitions; partition k starts at global round k*M.
    Surgeries last `duration` rounds.

    Intra-block pattern (every block b, offsets within the block):
      p0:  O_{6b+0} – O_{6b+3}
      p2:  O_{6b+0} – O_{6b+1}
      p4:  O_{6b+0} – O_{6b+1}
      p6:  O_{6b+0} – O_{6b+2}
      p8:  O_{6b+0} – O_{6b+4}
      p10: O_{6b+0} – O_{6b+5}

    Inter-block clock surgeries (chaining the O5 tail of each block):
      p12: O5  – O11   (block-0 tail vs block-1 tail)
      p12: O17 – O23   (block-2 tail vs block-3 tail)
      p15: O11 – O23   (merge the two above pairs)

    Returns a semicolon-separated spec string for parse_surgery_spec().
    """
    intra_pattern = [
        (0,  0, 3),
        (2,  0, 1),
        (4,  0, 1),
        (6,  0, 2),
        (8,  0, 4),
        (10, 0, 5),
    ]

    gates = []
    for block in range(4):
        base = 6 * block
        for part_idx, off_a, off_b in intra_pattern:
            gates.append((base + off_a, base + off_b, part_idx * M, duration))

    clock = [
        (5,  11, 12 * M, duration),
        (17, 23, 12 * M, duration),
        (11, 23, 15 * M, duration),
    ]
    gates.extend(clock)

    return ";".join(f"{a},{b},{s},{d}" for a, b, s, d in gates)

def build_surgery_spec_48obs(M=32, duration=21):
    """
    Generate the surgery spec string for the 48-observable, >19 partition circuit.

    48 observables in 8 blocks of 6 (block b = obs 6b..6b+5, b in 0..3).
    M=30 → 18 local partitions; partition k starts at global round k*M.
    Surgeries last `duration` rounds.

    Intra-block pattern (every block b, offsets within the block):
      p0:  O_{6b+0} – O_{6b+3}
      p2:  O_{6b+0} – O_{6b+1}
      p4:  O_{6b+0} – O_{6b+1}
      p6:  O_{6b+0} – O_{6b+2}
      p8:  O_{6b+0} – O_{6b+4}
      p10: O_{6b+0} – O_{6b+5}

    Inter-block clock surgeries (chaining the O5 tail of each block):
      p12: O5  – O11   (block-0 tail vs block-1 tail)
      p12: O17 – O23   (block-2 tail vs block-3 tail)
      p12: O29 – O35   (block-4 tail vs block-5 tail)
      p12: O41 – O47   (block-6 tail vs block-7 tail)
      p15: O11 – O23   (merge first two pairs)
      p15: O35 – O47   (merge second two pairs)
      p18: O23 – O47   (root merge)

    Returns a semicolon-separated spec string for parse_surgery_spec().
    """
    intra_pattern = [
        (0,  0, 3),
        (2,  0, 1),
        (4,  0, 1),
        (6,  0, 2),
        (8,  0, 4),
        (10, 0, 5),
    ]

    gates = []
    for block in range(8):
        base = 6 * block
        for part_idx, off_a, off_b in intra_pattern:
            gates.append((base + off_a, base + off_b, part_idx * M, duration))

    clock = [
        (5,  11, 12 * M, duration),
        (17, 23, 12 * M, duration),
        (29, 35, 12 * M, duration),
        (41, 47, 12 * M, duration),
        (11, 23, 15 * M, duration),
        (35, 47, 15 * M, duration),
        (23, 47, 18 * M, duration),
    ]
    gates.extend(clock)

    return ";".join(f"{a},{b},{s},{d}" for a, b, s, d in gates)


def parse_surgery_spec(spec_str, default_duration=1):
    """
    Parse a manual surgery spec string into a list of (obs_a, obs_b, start_round, duration).
    Format: semicolon-separated entries of "obs_a,obs_b,start[,duration]".
    Duration is optional and defaults to default_duration.
    Example: "0,1,3,2;0,2,7"  -> [(0,1,3,2), (0,2,7,1)]
    """
    gates = []
    for entry in spec_str.strip().split(";"):
        entry = entry.strip()
        if not entry:
            continue
        parts = entry.split(",")
        if len(parts) not in (3, 4):
            raise ValueError(
                f"Invalid surgery spec entry '{entry}'; expected 'obs_a,obs_b,start[,duration]'")
        obs_a, obs_b, start = int(parts[0]), int(parts[1]), int(parts[2])
        dur = int(parts[3]) if len(parts) == 4 else default_duration
        if obs_a == obs_b:
            raise ValueError(f"obs_a == obs_b in surgery spec '{entry}'")
        if dur < 1:
            raise ValueError(f"duration must be >= 1 in surgery spec '{entry}'")
        gates.append((min(obs_a, obs_b), max(obs_a, obs_b), start, dur))
    return gates


def main():
    parser = argparse.ArgumentParser(
        description="Generate a multi-observable matching graph DEM, optionally injecting "
                    "cross-observable lattice-surgery gates.")
    parser.add_argument("--rounds", type=int, required=True)
    parser.add_argument("--distance", type=int, required=True)
    parser.add_argument("--after_clifford_depolarization", type=float, default=0.01)
    parser.add_argument("--code", type=str, default="surface_code")
    parser.add_argument("--task", type=str, default="rotated_memory_x")
    parser.add_argument("--num_observables", type=int, default=2)

    surgery = parser.add_mutually_exclusive_group()
    surgery.add_argument("--num_surgery_gates", type=int, default=0,
                         help="Number of cross-observable surgery gates to inject, placed "
                              "randomly.  Each gate spans --surgery_duration rounds and "
                              "connects all boundary-site detector pairs along the shared "
                              "edge.")
    surgery.add_argument("--surgery_spec", type=str, default="",
                         help="Manual gate spec: semicolon-separated entries of the form "
                              "'obs_a,obs_b,start[,duration]' (duration defaults to "
                              "--surgery_duration).  Example: '0,1,3,2;0,2,7'.")
    surgery.add_argument("--surgery_preset", type=str, default="",
                         choices=["24obs", "48obs"],
                         help="Use a named preset surgery spec.  '24obs': 24-observable "
                              "756-round circuit with M=42, duration=21, 4 blocks of 6.")

    parser.add_argument("--surgery_duration", type=int, default=8,
                        help="Default number of rounds per surgery gate (default 8).")
    parser.add_argument("--surgery_seed", type=int, default=42,
                        help="RNG seed for --num_surgery_gates placement (default 42).")
    parser.add_argument("--p_cross", type=float, default=None,
                        help="Error probability for each injected seam error edge. "
                             "Defaults to min(0.4, 2 * after_clifford_depolarization) so seam "
                             "edges are lighter than boundary edges.")
    parser.add_argument("--surgery_boundary_depth", type=int, default=2,
                        help="x-distance from patch edge for selecting boundary detectors "
                             "(default 2).")
    parser.add_argument("--circuit_out", type=str, default="",
                        help="If given, write the single-observable base circuit to this file "
                             "for reference.  The output to stdout is always a DEM.")
    args = parser.parse_args()

    has_surgery = args.num_surgery_gates > 0 or args.surgery_spec or args.surgery_preset

    p_cross = args.p_cross if args.p_cross is not None else min(0.4, 2.0 * args.after_clifford_depolarization)

    base = stim.Circuit.generated(
        f"{args.code}:{args.task}",
        distance=args.distance,
        rounds=args.rounds,
        after_clifford_depolarization=args.after_clifford_depolarization
    )

    if args.circuit_out:
        with open(args.circuit_out, "w") as f:
            print(base, file=f)

    base_dem_flat = base.detector_error_model(decompose_errors=True).flattened()
    max_x = max(
        (inst.args_copy()[0] for inst in base_dem_flat
         if str(inst).startswith('detector(')),
        default=0.0)
    x_shift = max_x + 2

    obs_files = build_obs_temp_files(base_dem_flat, args.num_observables, x_shift)

    if not has_surgery:
        # No surgery: just concatenate observable files and output
        obs_paths = [obs_meta["path"] for obs_meta in obs_files]
        concat_files_to_stream(obs_paths, sys.stdout)
        cleanup_temp_files(obs_paths)
        return

    # Surgery path: parse index, generate gates, write seams, filter, concatenate
    ensure_perl_available()
    
    obs_round_dets, obs_rounds, x_extremes, max_detector_id = parse_obs_files_index(obs_files)
    
    if args.surgery_spec:
        surgery_gates = parse_surgery_spec(args.surgery_spec,
                                           default_duration=args.surgery_duration)
    elif args.surgery_preset == "24obs":
        surgery_gates = parse_surgery_spec(build_surgery_spec_24obs(),
                                           default_duration=args.surgery_duration)
    elif args.surgery_preset == "48obs":
        surgery_gates = parse_surgery_spec(build_surgery_spec_48obs(),
                                           default_duration=args.surgery_duration)
    else:
        available_rounds = build_available_rounds(obs_round_dets)
        surgery_gates = generate_random_surgery_gates(
            args.num_observables, available_rounds,
            args.num_surgery_gates,
            duration=args.surgery_duration,
            seed=args.surgery_seed)
    
    print(f"# Surgery gates: {surgery_gates}", file=sys.stderr)
    print(f"# p_cross: {p_cross:.6g}  (p={args.after_clifford_depolarization})",
          file=sys.stderr)
    
    # Write seams to temp file
    seam_path = None
    try:
        seam_path = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.dem').name
        with open(seam_path, 'w') as seam_file:
            seam_adjacent_by_obs = write_seams_to_temp_file(
                obs_round_dets, obs_rounds, x_extremes, surgery_gates,
                p_cross, args.surgery_boundary_depth,
                seam_start_det_id=max_detector_id + 1,
                seam_file=seam_file)
        
        # Filter boundary edges from impacted observables
        filter_impacted_obs_files_inplace(obs_files, seam_adjacent_by_obs)
        
        # Concatenate observable files + seam file to stdout
        obs_paths = [obs_meta["path"] for obs_meta in obs_files]
        concat_files_to_stream(obs_paths + [seam_path], sys.stdout)
        
    finally:
        obs_paths = [obs_meta["path"] for obs_meta in obs_files]
        if seam_path:
            obs_paths.append(seam_path)
        cleanup_temp_files(obs_paths)


if __name__ == '__main__':
    main()
